# -*- coding: utf-8 -*-
"""expert system.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1XO2zqEb9EYaMjthErxom68RE5SjMatE-
"""

import os


def clear_screen():
    os.system("cls" if os.name == "nt" else "clear")


def ask_yes_no(prompt):
    while True:
        response = input(prompt).lower().strip()
        if response in ["yes", "y", "no", "n"]:
            return response
        print("Please answer with 'yes' or 'no'.")


def get_level(prompt):
    while True:
        response = input(prompt).upper().strip()
        if response in ["LOW", "MEDIUM", "HIGH"]:
            return response
        print("Please answer with 'LOW', 'MEDIUM', or 'HIGH' only!")


# ================= HEADER =================
clear_screen()
print("+----------------------------------------------------------------+")
print("|                 Welcome to the Expert System Program           |")
print("|      Financial Recommendations Based on Investor Profile       |")
print("+----------------------------------------------------------------+\n")

name = input("Enter Your Name : ")
print(f"Welcome, {name}!")
choice = ask_yes_no(
    "Do you want to perform a financial self‑assessment?\n"
    "(Answer yes or no)\n: "
)

if choice in ["yes", "y"]:
    clear_screen()
    print("+----------------------------------------------------------------+")
    print("|                 Financial Recommendation System                |")
    print("+----------------------------------------------------------------+\n")

    print("Answer the following questions with: LOW, MEDIUM, or HIGH.\n")

    income_level = get_level("1. What is your INCOME LEVEL? (LOW/MEDIUM/HIGH): ")
    risk_level = get_level("2. What is your RISK TOLERANCE? (LOW/MEDIUM/HIGH): ")
    saving_level = get_level("3. What is your SAVINGS CAPACITY? (LOW/MEDIUM/HIGH): ")

    facts = [income_level, risk_level, saving_level]

    # ---------------- RULE BASE ----------------
    rule = {
        "STOCKS": ["HIGH", "HIGH", "HIGH"],
        "MUTUAL_FUND": ["MEDIUM", "MEDIUM", "MEDIUM"],
        "FIXED_DEPOSIT": ["MEDIUM", "LOW", "HIGH"],
        "EMERGENCY_FUND": ["HIGH", "HIGH", "LOW"],
        "LOW_RISK_INVEST": ["MEDIUM", "LOW", "MEDIUM"],
        "EQUITY_MUTUAL_FUND": ["HIGH", "MEDIUM", "HIGH"],
        "RETIREMENT": ["MEDIUM", "MEDIUM", "HIGH"],
        "GOVERNMENT_BONDS": ["HIGH", "HIGH", "MEDIUM"],
        "INSURANCE": ["HIGH", "LOW", "HIGH"],
        "NO_INVEST": ["LOW", "LOW", "LOW"]
    }

    # ---------------- FORWARD CHAINING ----------------
    def forward_chain(facts):
        score = {invest: 0 for invest in rule.keys()}
        for investment, conds in rule.items():
            matched = sum(
                1 for i, fact in enumerate(facts) if fact == conds[i]
            )
            score[investment] = matched

        max_score = max(score.values())
        best_matches = [
            invest for invest, s in score.items() if s == max_score
        ]

        if max_score == 0:
            return "No suitable investment recommendation found"
        elif len(best_matches) == 1:
            return f"{best_matches[0].replace('_', ' ').title()} (score: {max_score}/3)"
        else:
            names = ", ".join(b.replace("_", " ").title() for b in best_matches)
            return f"Possible: {names} (same score)"

    result = forward_chain(facts)

    # ================= RESULT BLOCK =================
    print("\n+----------------------------------------------------------------+")
    print("|                       RECOMMENDATION RESULT                    |")
    print("+----------------------------------------------------------------+")
    print(f"Name   : {name}")
    print(f"Result : {result}")
    print("+----------------------------------------------------------------+")
    print("|                 Thank you! Program finished.                   |")
    print("+----------------------------------------------------------------+")

else:
    print("\nYou chose not to continue the assessment.")
    print("+----------------------------------------------------------------+")
    print("|                 Thank you! Program finished.                   |")
    print("+----------------------------------------------------------------+")